# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # fileSystems."/.swapvol" =
  #   { device = "/dev/mapper/crypted";
  #     fsType = "btrfs";
  #     options = [ "subvol=@swap" ];
  #   };

  # boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/9d9cc9ac-bef3-4191-9a32-8c004ab2f8b8";
  #
  # fileSystems."/boot" =
  #   { device = "/dev/disk/by-uuid/8136-971D";
  #     fsType = "vfat";
  #     options = [ "fmask=0077" "dmask=0077" ];
  #   };
  #
  # fileSystems."/home" =
  #   { device = "/dev/mapper/crypted";
  #     fsType = "btrfs";
  #     options = [ "subvol=@home" ];
  #   };
  #
  # fileSystems."/nix" =
  #   { device = "/dev/mapper/crypted";
  #     fsType = "btrfs";
  #     options = [ "subvol=@nix" ];
  #   };
  #
  # fileSystems."/persistent" =
  #   { device = "/dev/mapper/crypted";
  #     fsType = "btrfs";
  #     options = [ "subvol=@persistent" ];
  #   };
  #
  # swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
